# Generated by Django 5.0.3 on 2024-09-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='challan_no',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='email',
            new_name='quarry',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='royalty_pass',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='truck_no',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
    ]
